{
  "openapi": "3.1.0",
  "info": {
    "title": "API de Autenticaci贸n de Usuario",
    "description": "API para generar una URL de autenticaci贸n y verificar el estado de un ticket de validaci贸n.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.ejemplo.com/v1",
      "description": "Servidor de Producci贸n"
    }
  ],
  "paths": {
    "/business": {
      "post": {
        "parameters": [
          {
            "description": "Flag to enable mock mode",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            },
            "name": "mock",
            "in": "query"
          },
          {
            "description": "The merchant ID in UUID format",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "name": "x-merchant-id",
            "in": "header"
          }
        ],
        "requestBody": {
          "description": "The validation request payload",
          "content": {
            "application/json": {
              "examples": {
                "RequestExample": {
                  "value": {
                    "name": "Juan Perez",
                    "phoneNumber": "+51934567890",
                    "documentType": "pe-dni",
                    "documentNumber": "12345678",
                    "successRedirectUrl": "https://example.com/success",
                    "failureRedirectUrl": "https://example.com/error"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/ValidationRequestDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Identity verification created successfully",
            "content": {
              "application/json": {
                "examples": {
                  "SuccessResponse": {
                    "value": {
                      "message": "success",
                      "data": {
                        "id": "72e7918a-5aaa-4b7c-a471-23c5800c0e4e",
                        "name": "Juan Perez",
                        "documentType": "pe-dni",
                        "documentNumber": "12345678",
                        "publicId": "01971cb5-4751-7582-b256-bbe0df60f0e4",
                        "status": "PENDING",
                        "partnerChannel": "Keynua",
                        "partnerNote": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...",
                        "merchantId": "01890f3b-7c9a-7b4b-8c9a-7b4b8c9a7b4b",
                        "successRedirectUrl": "https://example.com/success",
                        "failureRedirectUrl": "https://example.com/error"
                      }
                    }
                  }
                },
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ApiResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/ValidationRequestDto"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "summary": "Create Identity Verification",
        "tags": [
          "Business Controller"
        ],
        "security": [
          {
            "defaultApiKey": []
          }
        ]
      }
    },
    "/get-state/{publicId}": {
      "get": {
        "tags": [
          "State Validation"
        ],
        "parameters": [
          {
            "description": "The merchant ID associated with the request",
            "name": "x-merchant-id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "header"
          },
          {
            "description": "The public ID of the validation ticket",
            "name": "publicId",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved the validation ticket",
            "content": {
              "application/json": {
                "examples": {
                  "SuccessResponse": {
                    "value": {
                      "message": "success",
                      "data": {
                        "id": "cb8a9360-02c4-4c38-9edd-858e504d8393",
                        "documentNumber": "87654321",
                        "documentType": "pe-dni",
                        "merchantId": "01890f3b-7c9a-7b4b-8c9a-7b4b8c9a7b4b",
                        "name": "Pedro Martinez",
                        "partnerChannel": "Keynua",
                        "partnerNote": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjaWQiOiJlYTY0ZTYxMC0zYjMyLTExZjAtODEyNi00YjhmYzI0YjAyNjNlMSIsInRva2VuX3VzZSI6InNpZ24iLCJpc3MiOiJodHRwczovL2FwaS5zdGcua2V5bnVhLmNvbS9jb250cmFjdHMiLCJ1aWQiOjAsInBpZCI6ImMyNWFlMTBmMTBlYTJkZjhlYjBjZGI5YzMzOWQ5Yjk4NjY3M2Y4ZGRmZWMzYzZhOTQ2MWUwYWNlYWE2NjJmNzcifQ.2y2eItaSwCyonxPwvFBoM92xkr7xAgomCP5CaE8uXb4",
                        "publicId": "019718be-0774-7bcf-ac23-e602c3eecd55",
                        "status": "PENDING",
                        "successRedirectUrl": "https://example.com/success",
                        "failureRedirectUrl": "https://example.com/error"
                      }
                    }
                  }
                },
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ApiResponse"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/ValidationTicket"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "summary": "Get By Id",
        "security": [
          {
            "defaultApiKey": []
          }
        ]
      }
    }
  },
  "webhooks": {
    "/webhook/keynua": {
      "post": {
        "requestBody": {
          "description": "The received webhook data.",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "type",
                  "accountId",
                  "payload"
                ],
                "properties": {
                  "type": {
                    "$ref": "#/components/schemas/WebhookType"
                  },
                  "accountId": {
                    "type": "string"
                  },
                  "payload": {
                    "$ref": "#/components/schemas/WebhookPayload"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": [
                    "message"
                  ],
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "success"
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Webhook",
        "tags": [
          "Webhook Keynua Controller"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "defaultApiKey": {
        "type": "apiKey",
        "description": "20 character string",
        "name": "authorization",
        "in": "header"
      }
    },
    "schemas": {
      "ApiResponse": {
        "type": "object",
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "type": "string"
          },
          "data": {}
        }
      },
      "ValidationRequestDto": {
        "type": "object",
        "required": [
          "name",
          "phoneNumber",
          "documentType",
          "documentNumber"
        ],
        "properties": {
          "name": {
            "type": "string",
            "maxLength": 50,
            "pattern": "\\S"
          },
          "phoneNumber": {
            "type": "string",
            "minLength": 12,
            "maxLength": 12,
            "pattern": "\\S"
          },
          "documentType": {
            "type": "string",
            "pattern": "pe-dni"
          },
          "documentNumber": {
            "type": "string",
            "pattern": "\\d{8}"
          },
          "successRedirectUrl": {
            "type": "string",
            "format": "uri"
          },
          "failureRedirectUrl": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "ValidationTicket": {
        "type": "object",
        "required": [
          "name",
          "documentType",
          "documentNumber",
          "publicId",
          "status",
          "partnerChannel",
          "partnerNote",
          "merchantId",
          "successRedirectUrl",
          "failureRedirectUrl"
        ],
        "properties": {
          "id": {
            "type": [
              "string"
            ]
          },
          "name": {
            "type": "string"
          },
          "documentType": {
            "type": "string"
          },
          "documentNumber": {
            "type": "string"
          },
          "publicId": {
            "type": "string",
            "format": "uuid"
          },
          "status": {
            "$ref": "#/components/schemas/ValidationTicketStatus"
          },
          "partnerChannel": {
            "type": "string"
          },
          "partnerNote": {
            "type": "string"
          },
          "merchantId": {
            "type": "string",
            "format": "uuid"
          },
          "successRedirectUrl": {
            "type": "string",
            "format": "uri"
          },
          "failureRedirectUrl": {
            "type": "string",
            "format": "uri"
          }
        }
      },
      "ValidationTicketStatus": {
        "type": "string",
        "enum": [
          "PENDING",
          "FAILED",
          "SUCCESS"
        ]
      },
      "IdentityVerificationCreatedDto": {
        "type": "object",
        "required": [
          "language",
          "reference",
          "contractId",
          "documentNumber",
          "id",
          "accountId",
          "createdAt",
          "accountEmail",
          "organizationId",
          "accountName",
          "title"
        ],
        "properties": {
          "language": {
            "type": "string"
          },
          "reference": {
            "type": "string"
          },
          "contractId": {
            "type": "string"
          },
          "documentNumber": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "accountId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "accountEmail": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          },
          "accountName": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        }
      },
      "IdentityVerificationFinishedDto": {
        "type": "object",
        "required": [
          "language",
          "reference",
          "contractId",
          "documentNumber",
          "id",
          "accountId",
          "createdAt",
          "startedAt",
          "accountEmail",
          "organizationId",
          "accountName",
          "title",
          "userEmail",
          "userPhone",
          "userToken",
          "userIdInfo",
          "alerts"
        ],
        "properties": {
          "language": {
            "type": "string"
          },
          "reference": {
            "type": "string"
          },
          "contractId": {
            "type": "string"
          },
          "documentNumber": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "accountId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "startedAt": {
            "type": "string"
          },
          "accountEmail": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          },
          "accountName": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "userEmail": {
            "type": "string"
          },
          "userPhone": {
            "type": "string"
          },
          "userToken": {
            "type": "string"
          },
          "userIdInfo": {
            "type": "string"
          },
          "alerts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/KeynuaVerificationAlertDto"
            }
          }
        }
      },
      "IdentityVerificationStartedDto": {
        "type": "object",
        "required": [
          "language",
          "reference",
          "contractId",
          "documentNumber",
          "id",
          "accountId",
          "createdAt",
          "startedAt",
          "accountEmail",
          "organizationId",
          "accountName",
          "title",
          "userEmail",
          "userPhone",
          "userToken"
        ],
        "properties": {
          "language": {
            "type": "string"
          },
          "reference": {
            "type": "string"
          },
          "contractId": {
            "type": "string"
          },
          "documentNumber": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "accountId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "startedAt": {
            "type": "string"
          },
          "accountEmail": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          },
          "accountName": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "userEmail": {
            "type": "string"
          },
          "userPhone": {
            "type": "string"
          },
          "userToken": {
            "type": "string"
          }
        }
      },
      "KeynuaVerificationAlertDataDto": {
        "type": "object",
        "required": [
          "code",
          "dni"
        ],
        "properties": {
          "code": {
            "type": "string"
          },
          "userId": {
            "type": "integer",
            "format": "int32"
          },
          "dni": {
            "type": "string"
          }
        }
      },
      "KeynuaVerificationAlertDto": {
        "type": "object",
        "required": [
          "type",
          "data"
        ],
        "properties": {
          "type": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/KeynuaVerificationAlertDataDto"
          }
        }
      },
      "WebhookPayload": {
        "type": "object",
        "description": "Payload of the webhook. The type of the payload depends on the type of the webhook.",
        "discriminator": {
          "propertyName": "type",
          "mapping": {
            "IdentityVerificationCreated": "#/components/schemas/IdentityVerificationCreatedDto",
            "IdentityVerificationStarted": "#/components/schemas/IdentityVerificationStartedDto",
            "IdentityVerificationFinished": "#/components/schemas/IdentityVerificationFinishedDto"
          }
        }
      },
      "WebhookType": {
        "type": "string",
        "enum": [
          "IDENTITY_VERIFICATION_CREATED",
          "IDENTITY_VERIFICATION_STARTED",
          "IDENTITY_VERIFICATION_FINISHED"
        ]
      }
    }
  }
}
